{{- if .Values.writes.openTelemetry.enabled }}
{{- range $rsName, $rs := .Values.writes.openTelemetry.remoteStorages }}
{{- if not $rs.writeURL }}
{{- fail (printf "writes.openTelemetry.remoteStorages.%s.writeURL must be specified when writes.openTelemetry.enabled is true" $rsName) }}
{{- end }}
{{- $writeURLs := $rs.writeURL | splitList "," }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-benchmark.fullname" $ }}-otel-collector-{{ $rsName }}-cm
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "prometheus-benchmark.labels" $ | nindent 4 }}
data:
  config.yaml: |
    receivers:
      host_metrics:
        collection_interval: {{ $.Values.writes.openTelemetry.scrapeInterval }}
        scrapers:
          cpu:
          disk:
          load:
          filesystem:
          memory:
          network:
          paging:

    processors:
    {{- range $i := until (int $.Values.writes.openTelemetry.targetsCount) }}
      transform/replica_{{ add $i 1 }}:
        metric_statements:
          - context: datapoint
            statements:
              - set(attributes["otel_source_id"], "instance-{{ add $i 1 }}")
    {{- end }}

    exporters:
    {{- range $idx, $url := $writeURLs }}
      otlp_http/{{ $rsName }}_{{ $idx }}:
        compression: gzip
        encoding: proto
        metrics_endpoint: {{ trim $url }}
        tls:
          insecure: true
    {{- end }}

    service:
      telemetry:
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: '0.0.0.0'
                    port: 8888
      pipelines:
    {{- $exporterList := list }}
    {{- range $idx, $_ := $writeURLs }}
    {{- $exporterList = append $exporterList (printf "otlp_http/%s_%d" $rsName $idx) }}
    {{- end }}
    {{- range $i := until (int $.Values.writes.openTelemetry.targetsCount) }}
        metrics/replica_{{ add $i 1 }}:
          receivers: [host_metrics]
          processors: [transform/replica_{{ add $i 1 }}]
          exporters: [{{ join ", " $exporterList }}]
    {{- end }}
---
{{- end }}
{{- end }}
