{{- if .Values.writes.openTelemetry.enabled }}
{{- range $rsName, $rs := .Values.writes.openTelemetry.remoteStorages }}
{{- $total := $.Values.writes.openTelemetry.targetsCount | int }}
{{- $chunkSize := 3000 }}
{{- $chunks := divf $total $chunkSize | ceil | int }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-benchmark.fullname" $ }}-otel-collector-{{ $rsName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "prometheus-benchmark.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      job: otel-collector
      remote-storage-name: {{ $rsName | quote }}
      {{- include "prometheus-benchmark.selectorLabels" $ | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/otel-collector/cm.yaml") $ | sha256sum }}
      labels:
        job: otel-collector
        remote-storage-name: {{ $rsName | quote }}
        {{- include "prometheus-benchmark.labels" $ | nindent 8 }}
    spec:
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: otel-collector
        image: "otel/opentelemetry-collector-contrib:{{ $.Values.writes.openTelemetry.collectorImageTag }}"
        args:
        - --config=/config/base/config.yaml
        {{- range $chunkIdx := until $chunks }}
        - --config=/config/chunk-{{ $chunkIdx }}/config.yaml
        {{- end }}
        ports:
        - name: metrics
          containerPort: 8888
        volumeMounts:
        - name: config-base
          mountPath: /config/base
        {{- range $chunkIdx := until $chunks }}
        - name: config-chunk-{{ $chunkIdx }}
          mountPath: /config/chunk-{{ $chunkIdx }}
        {{- end }}
      volumes:
      - name: config-base
        configMap:
          name: {{ include "prometheus-benchmark.fullname" $ }}-otel-collector-{{ $rsName }}-cm-base
      {{- range $chunkIdx := until $chunks }}
      - name: config-chunk-{{ $chunkIdx }}
        configMap:
          name: {{ include "prometheus-benchmark.fullname" $ }}-otel-collector-{{ $rsName }}-cm-{{ $chunkIdx }}
      {{- end }}
---
{{- end }}
{{- end }}