{{- if .Values.reads.enabled }}
{{ range $rsName, $rs := .Values.reads.remoteStorages }}
{{- if not $rs.readURL }}
{{- fail (printf "reads.remoteStorages.%s.readURL must be specified when reads.enabled is true" $rsName) }}
{{- end }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus-benchmark.fullname" $ }}-vmalert-{{ $rsName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "prometheus-benchmark.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      job: vmalert
      remote-storage-name: {{ $rsName | quote }}
      {{- include "prometheus-benchmark.selectorLabels" $ | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        checksum/vmalert-cm: {{ include (print $.Template.BasePath "/vmalert/vmalert-cm.yaml") $ | sha256sum }}
      labels:
        job: vmalert
        remote-storage-name: {{ $rsName | quote }}
        {{- include "prometheus-benchmark.labels" $ | nindent 8 }}
    spec:
      {{- with $.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: vmalert
        image: "victoriametrics/vmalert:{{ $.Values.vmtag }}"
        {{- with $rs.vmalertExtraEnvs }}
        env:
        {{- toYaml . | nindent 10 }}
        {{- end }}
        args:
        - --httpListenAddr=:8880
        - --notifier.blackhole=true
        - --rule=/config/alerts.yml
        - --evaluationInterval={{ $.Values.reads.queryInterval }}
        - --datasource.url={{ $rs.readURL }}
        {{- if $rs.bearerToken }}
        - --datasource.bearerToken={{ $rs.bearerToken }}
        {{- end }}
        {{- if $rs.headers }}
        - --datasource.headers={{ $rs.headers }}
        {{- end }}
        {{- range $rs.vmalertExtraFlags }}
        - {{ . }}
        {{- end }}
        ports:
        - name: metrics
          containerPort: 8880
        volumeMounts:
        - name: vmalert-cfg
          mountPath: /config
      volumes:
      - name: vmalert-cfg
        configMap:
          name: {{ include "prometheus-benchmark.fullname" $ }}-vmalert-cm
---
{{ end }}
{{- end }}
